### ISSUE TITLE
Consider Using Docker Compose for Testing/Development

### ISSUE THREAD

**Issue by adamgoose** [Nexmo/nexmo-nodered#42]
This is only an idea, so feel free to close this issue right away. After reading your `testing.md` file, I realized that you're doing the same thing I am with docker-compose. The added benefit of using docker-compose is that the docker commands can be easily shared via a `docker-compose.yml` file, and you can easily mount your local dev copy into the container. This allows you to both test and develop the nodes at the same time from your host.

```yaml
version: '3'
services:
  nodered:
    image: nodered/node-red-docker:0.19.5-v8
    ports:
    - 1880:1880
    volumes:
    - .:/local # Your local working copy
    - ./data:/data # Persist configuration between sessions
```

The following commands accompany this setup:

- `docker-compose up -d` - Bring up the dev environment
- `docker-compose exec -w /data nodered npm i /local` - Install your local working copy as nodes
- `docker-compose restart` - Restart NodeRED (after `npm i` and any source code changes)
- `docker-compose exec nodered bash` - Get a shell into the container

`/data` should probably be added to `.gitignore`, since its just your local NodeRED installation.
